version: "3"
services:
    front:
        build:
            context: ./client
        container_name: front-container
        ports:
            - "5173:5173"
        restart: unless-stopped

    backend:
        build:
            context: ./server
        container_name: backend-container
        ports:
            - "3000:3000"
        restart: unless-stopped
